const doctors = [
  {
    id: 1,
    firstname: "John",
    lastname: "Doe",
    specialty: "cardiologist",
    hospital: "City Hospital",
    location: { lat: 40.7128, lng: -74.006 }, // New York City
    experience: 10, // years of experience
    rating: 4.8, // Doctor's rating out of 5
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ], // Available all days
  },
  {
    id: 2,
    firstname: "Jane",
    lastname: "Smith",
    specialty: "dermatologist",
    hospital: "Town Hospital",
    location: { lat: 34.0522, lng: -118.2437 }, // Los Angeles
    experience: 7,
    rating: 4.5,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 3,
    firstname: "Emily",
    lastname: "Brown",
    specialty: "cardiologist",
    hospital: "General Hospital",
    location: { lat: 37.7749, lng: -122.4194 }, // San Francisco
    experience: 12,
    rating: 4.9,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 4,
    firstname: "Michael",
    lastname: "Green",
    specialty: "neurologist",
    hospital: "Neuro Health Clinic",
    location: { lat: 41.8781, lng: -87.6298 }, // Chicago
    experience: 15,
    rating: 4.7,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 5,
    firstname: "Sarah",
    lastname: "Johnson",
    specialty: "pediatrician",
    hospital: "Children's Health Center",
    location: { lat: 29.7604, lng: -95.3698 }, // Houston
    experience: 8,
    rating: 4.6,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 6,
    firstname: "David",
    lastname: "Lee",
    specialty: "orthopedist",
    hospital: "Ortho Care Center",
    location: { lat: 34.0522, lng: -118.2437 }, // Los Angeles
    experience: 11,
    rating: 4.3,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 7,
    firstname: "Angela",
    lastname: "White",
    specialty: "cardiologist",
    hospital: "Heart Specialist Clinic",
    location: { lat: 40.7128, lng: -74.006 }, // New York City
    experience: 14,
    rating: 4.9,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 8,
    firstname: "Robert",
    lastname: "Wilson",
    specialty: "dermatologist",
    hospital: "Skin Care Clinic",
    location: { lat: 47.6062, lng: -122.3321 }, // Seattle
    experience: 6,
    rating: 4.4,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 9,
    firstname: "Lisa",
    lastname: "Brown",
    specialty: "neurologist",
    hospital: "Brain Health Center",
    location: { lat: 37.7749, lng: -122.4194 }, // San Francisco
    experience: 13,
    rating: 4.8,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 10,
    firstname: "Chris",
    lastname: "Miller",
    specialty: "orthopedist",
    hospital: "Advanced Ortho Clinic",
    location: { lat: 34.0522, lng: -118.2437 }, // Los Angeles
    experience: 9,
    rating: 4.5,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 11,
    firstname: "Karen",
    lastname: "Taylor",
    specialty: "pediatrician",
    hospital: "Children's Hospital",
    location: { lat: 25.7617, lng: -80.1918 }, // Miami
    experience: 10,
    rating: 4.7,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  {
    id: 12,
    firstname: "Paul",
    lastname: "Jones",
    specialty: "neurologist",
    hospital: "Brain Health Institute",
    location: { lat: 39.7392, lng: -104.9903 }, // Denver
    experience: 16,
    rating: 4.8,
    availability: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
];

module.exports = { doctors };
